### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by calebcoverdale** [sb-ocr/ocreeb-mk-2#2]
Hey there,

Just noticed your project doesn’t have a license file. Thought I’d mention that adding a license could be really beneficial, especially for a cool project like this. A license helps protect your work from being copied or misused. It also makes it clear how others can use, modify, or distribute your design.

I wasn't stepping on your work. It's truly what I've been looking to play with. I have lots of boards, sensors, but this finally pulls it altogether. 

Thanks so much for your work on this! 

I'm printing the files as we speak so I can start to tinker!

**Comment by DemonChicken1111** [comment]
I was also wondering about this! Thanks for putting the question out!

**Comment by sb-ocr** [comment]
Hey, thanks for letting me know. I usually do, but I forgot when I was frantically uploading the repo the other day. I'm still working on the build instructions, and I will update and clean up the project in the upcoming days. In the meantime, I have added the licenses for anyone wanting to tinker with this. 

Thanks again for bringing this to my attention!
