### ISSUE TITLE
CAD files

### ISSUE THREAD

**Issue by Rom4ik-glitch** [sb-ocr/ocreeb-mk-2#3]
Hi. Can you please update CAD/STL sections with .step files? i would like to make a my own macropads and modules based on your design

**Comment by XEJK** [comment]
I would also be very interested in this.

**Comment by sb-ocr** [comment]
Uploaded Step files. Lmk if you need anything else.

**Comment by Rom4ik-glitch** [comment]
Also, i know, am asking a lot, but could you please upload schematics of modules in pdf? i want to see for any ability to improve interface perfomance, for example, by implementing CAN interface, ore smth like that, so need to see whats inside the box :)

**Comment by sb-ocr** [comment]
@Rom4ik-glitch Done! I uploaded the PDFs and files if you want to change them in Eagle or Fusion
