### ISSUE TITLE
Core and modules schematic files

### ISSUE THREAD

**Issue by Art3mis0940** [sb-ocr/ocreeb-mk-2#5]
Hey! Can I ask you to attach schematic files of the boards for the Core and Modules, as was the case for the first version of the macropad?

**Comment by magicfr** [comment]
Hi, Great job ... I will also be very interrested in the schematic files for the board. Could you share with us ?

**Comment by sb-ocr** [comment]
Hey, I shared the Schematics and board files (Eagle 9.x / Fusion). I included PDFs as well incase you just want to peak
