### ISSUE TITLE
Cannot get main macropad module to type 

### ISSUE THREAD

**Issue by DemonChicken1111** [sb-ocr/ocreeb-mk-2#6]
Hey! I have currently finished building the main macro-pad module. I have put the firmware code on the board, and I have checked my soldering a few times now. I cannot get the RGB to light up (The OLED works fine), and the board is constantly inputting strokes into my computer. I am not sure what is causing the issue. Here is my testing keymap in main.py:

`keyboard.keymap = [
    [
        KC.A,     KC.B,      KC.C,      KC.D,
        KC.E,     KC.F,      KC.G,      KC.H,
        KC.I,     KC.J,      KC.K,      KC.L,
    ]   # Layer 1
]`

Here is my output in a random text editor when this is saved to the board: (Note I am trying to push buttons, hold buttons etc, to try and get this to stop, which is where the new/random other letters start appearing)

`ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddiddjdklefdghlghbeaddlfcdgaddjkldefghdadibcddgaddjklefgdhadibdcdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddgaijklefghadddddddddddddddlbcjijklefghaddddddddddlbcjijklefghaddddddddddddddddddddddddlbcgaklefghaijjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjbcdiijklefghaddddddddddddddlbcjijklefghadlbcgaijklefghadddddddddddddddddddddddddddddlbcgaijklefghadlbcgaklefghaijjjjjjjjjjjjjjjjjjjjjjjjjjjabcdgjklefghaiabgijklefghadddddddddddddddddddddddddddddddlbcjijklefghaddddddddddddddddddddddddddddddddddlj`

And here is my soldering work:

![IMG_0585](https://github.com/sb-ocr/ocreeb-mk-2/assets/77633123/7d1595fe-65eb-47e9-a884-7fa1993863f6)

I'm not sure if you have encountered this issue, however I would like to resolve this issue. If you need any more files, code snippets, or log files let me know.

-Demon

**Comment by sb-ocr** [comment]
Hey, at first glance, it seems like a soldering issue. You appear to have a bridge in one of the shift registers, and this is also consistent with the behavior you are describing. I would look there first and probe all the pins against the switches to make sure they are soldered properly and not bridging. As I mentioned in the video, the footprint I chose for the shift registers was kind of tight and was a pain to solder properly.
![Screenshot 2024-02-25 at 2 08 41 PM](https://github.com/sb-ocr/ocreeb-mk-2/assets/99417980/00921a5c-6ed0-4f1a-be8f-ec6e59e72788)

The Neopixels are soldered backwards. The notch needs to align with the diagonal line on the silkscreen.
![Screenshot 2024-02-25 at 2 09 09 PM](https://github.com/sb-ocr/ocreeb-mk-2/assets/99417980/518a7fad-93ff-4ef9-805d-61311c3ea56d)
Best of luck!

**Comment by DemonChicken1111** [comment]
Thank you for the clarification on the LED's. Don't know how I missed that diagonal mark on the silkscreen lol. The bridging was the cause of the issue. One of the shift registers was bridged underneath the visible part of the chip (which was mostly part of my confusion looking for the bridges). Reflowing it, taking it off, and fixing the bridge solved my issues. Thank you!
