### ISSUE TITLE
Nice Work!

### ISSUE THREAD

**Issue by Attempt3035** [sb-ocr/ocreeb-mk-2#8]
@sb-ocr You wouldn't believe it, I did a school Design & Tech major works on this concept a few years back, you've implemented pretty much everything I ideated right down to the custom pogo pin connectors, only I did a base mounting board design. Sharing some of my old files here as they might be of interest! Obviously it's not super technical as it had to fit within particular marking guidelines and cover particular topics, but I'm sure you'll enjoy the blender render promo video that looks remarkably like the one in your youtube vid! If you ever decide to do a version 3, I'd love to have a chat, I've got other projects on at the moment but still would love to make this a reality for the live production / DJ space! Love your work!

[MIDIFIER Design Folio.pdf](https://github.com/sb-ocr/ocreeb-mk-2/files/14556556/MIDIFIER.Design.Folio.pdf)

https://github.com/sb-ocr/ocreeb-mk-2/assets/118163872/76b48793-5354-4200-937b-a4abdcf1b80e

**Comment by sb-ocr** [comment]
Nice! yeah it does look very similar! Good job and thanks for sharing.
